### ISSUE TITLE
🌟 [EPIC] Neue Version der busFaktor()-Vereins-Webseite

### ISSUE THREAD

**Issue by Tirokk** [busFaktor/website#2]
## 🌟 EPIC

Neue Version der busFaktor()-Vereins-Webseite mit Grav CMS auf YunoHost aufsetzen

##### Höhere Priorität
- [x] Inhalte strukturieren: Überschriften, Wellenlinie (hr-Tags)
- [x] Lizenz erwähnen, siehe z. B. https://www.iconfinder.com/icons/8679389/discord_fill_icon
- [x] Home: Hero hinzufügen, Rahmen unter Kopfzeile entfernen?
- [ ] Diverse Seiten v.a. Projekte: Bilder/Illustrationen/Icons einfügen, Kacheln
- [ ] Home: Links bei Beitragsvorschau
- [x] Erklärung "Warum *busFaktor*" anfügen

##### Tiefere Priorität

- [ ] Design
  - [x] Social Media Icons in Fußzeile hinzufügen, siehe 'Notizen'
    - [x] SVG-Icons hochladen
    - [x] CSS anfügen, analog hier https://discourse.getgrav.org/t/how-to-use-font-awesome-line-awesome-in-quark/12979/6
    - [x] Lizenz erwähnen, siehe z. B. https://www.iconfinder.com/icons/8679389/discord_fill_icon
  - [x] Schickere Kästen, abgerundete Ecken oder nur Border, oder so?!
  - [x] Design-Session mit Max.
    - [x] Home: Hero hinzufügen, Rahmen unter Kopfzeile entfernen?
    - [ ] Diverse Seiten v.a. Projekte: Bilder/Illustrationen/Icons einfügen, Kacheln
    - [x] Inhalte strukturieren: Überschriften, Wellenlinie (hr-Tags)
    - [x] Mehr Kästchen mit Überschrift
    - [ ] Home: Links bei Beitragsvorschau
    - [x] Footer: Farbkonzept für Links
    - [ ] Allgemein mehr Inhalte und Call to Actions. (Projekte, Mitmachen)
    - [x] Neuer Bus? https://img.freepik.com/premium-photo/vintage-style-vintage-bus-vector-illustration_899449-182259.jpg
    - [x] Der Bus könnte aus meiner Sicht auch so bleiben, wenn der Rest der Webseite genauso schnörkelige Linien bekäme.
    - [x] Erklärung "Warum *busFaktor*" anfügen
    - [ ] Home: Männchen im Bus erscheinen beim Scrollen
    - [x] Passende Laufschrift => Max
  - [x] Design für kleine Bildschirme
- [ ] GRAV-Software aktualisieren
- [ ] Sprache 
  - [ ] Englische Übersetzung
  - [ ] Sprachumschalter hinzufügen
- [ ] Blog-Beitragssortierung nach veröffentlichungsdatum 

#### Zwecke der Website

- [ ] Selbstdarstellung
- [ ] Projekte vorstellen
- [ ] Spenden einwerben
- [ ] Veranstaltungen veröffentlichen
- [ ] Blog 
- [ ] Verbreitung von Infos
- [ ] Akquise von Mitgliedern, Förderern, Betreibern, Entwickeln, Sysadmin
- [ ] Organiseren und Koordinieren
- [ ] Vernetzen
- [ ] Crowdsourcing
- [ ] Backup/Ausfallsicherung für Projekte, busFaktor erhöhen, Innendienst, Projektinitiator entlasten, mehr Sicherheit für Auftraggeber, Betreiber und Nutzer, Nachhaltigkeit der FOSSware
- [ ] Bildung zugunsten gemeinnütziger Zwecke
- [ ] Verbreiten von FOSSware (FOSS.network), Quellcode, Lernmaterial, Git
- [ ] Technische Unterstützung z.B. Beratung
- [ ] Aufklärung über Datenschutz/Inforamtionssicherheit 
- [ ] Erfahrungsaustausch (TechDays)
- [ ] Unterstützen

#### Zielgruppen  

- [ ] Entwickler
- [ ] Sysadmins
- [ ] Betreiber 
- [ ] Förderer
- [ ] Fördermitglieder gewinnen
- [ ] Anwender
- [ ] Spender gewinnen
- [ ] Aktivmitglieder gewinnen ist nicht primäres Ziel

#### Seitenstruktur

- [x] Home: Selbstdarstellung in Kurzform als Übersicht, Latest News
  - [x] Neues Logo hinzufügen
- [x] Blog/News
- [x] Veranstaltungen
- [x] Projekte mit Unterseiten
  - [x] Tech-Day
  - [x] Ocelot.social
  - [x] UtopiaMap 
- [x] Events/Termine
- [x] Verein/Über uns 
  - [x] Satzung
  - [x] Gebühren
  - [ ] Mitglieder
  - [x] Mitgliedschaft
- [x] Mitmachen
- [ ] Spenden
  - [x] Optimieren der Spendenseite
  - [x] Adresse für Spender aus der Schweiz z.B.: Wiedemannstr. 15 1/2, 86343 Königsbrunn
  - [ ] PayPal?
  - [ ] LiberaPay?
  - [ ] Bitcoin?
  - [ ] QR-Code?
- [ ] Kontakt
  - [x] Seite neu
  - [ ] Neue Anschrift 
  - [x] Discord-Server: https://discord.gg/2b55aHVgpM
- [x] Datenschutzseite
- [ ] Impressum
  - [ ] Neue Anschrift 
  - [ ] Neues Registergericht

#### Entwicklung

- [ ] Footer Menu:
  - [x] Links zu den Seiten Datenschutz und Impressum in der Fußzeile zeigen
  - [x] Diese Menüpunkte im Hauptmenü für Desktops verstecken
  - [ ] Durch echtes Menü ersetzen: 
    https://github.com/getgrav/grav-premium-issues/issues/190  
    https://discourse.getgrav.org/t/footer-menu/3447  
    https://learn.getgrav.org/17/content/taxonomy
- [ ] Haupt-Domain von `www.busfaktor.org` auf `busfaktor.org` umstellen
- [ ] Lang-Switcher aktivieren:
  - im Template: siehe https://github.com/getgrav/grav-plugin-langswitcher?tab=readme-ov-file#usage
- [ ] Events: Mit Event-Plugin
- [x] Mobil
  - [x] Seitenränder zu klein auf Mobil, siehe Screenshots
- [ ] Bug: Theme-Name im Backend zum Auswählen?
- [ ] Dunkel-Modus

#### Notizen

- [x] Link zu YouTube-Kanal-URL mit Alias: https://www.youtube.com/@busfaktor
- [x] Social-Media-Icons in der Fußzeile
- [x] neue Ankündigungsseite für Veranstaltungen: Tech-Day Vortragsreihe
- [x] Adresse aktualisieren: Wiedemannstr. 15 1/2, 86343 Königsbrunn
- [ ] Präsenz auf fosstodon.org?

<img width="321" alt="IMG_0056" src="https://github.com/user-attachments/assets/7cb7add6-3ec0-4fe4-ab26-d2f6160b0440">
<img width="321" alt="IMG_0055" src="https://github.com/user-attachments/assets/ffd1b253-955b-4a00-837f-78ea588db225">

**Comment by Tirokk** [comment]
Max hat folgendes angemerkt:

Gibt es auch noch die Möglichkeit, die alte Version anzuschauen als Referenz?
Ansonsten hab ich mir jetzt auch ein paar Notizen gemacht. Bin nicht sicher wohin damit - gibt es einen Channel?

Hier schon mal: - Der Bus!! Viel zu schwammig. Vielleicht etwas wie https://img.freepik.com/premium-photo/vintage-style-vintage-bus-vector-illustration_899449-182259.jpg (ich weiß, Lizenzen und so... vielleicht lässt sich eine kostenlose Grafik finden oder ein echtes Foto mit einem Tool verfremden)
    
Inhaltlich: Unklar, zu schnell in Nebensatz abgehandelt: Was ist FOSS? Wieso FOSS?
Beispiel: https://www.fossware.dev/ (dort wird der User mE besser abgeholt)
Design (nachdem Aufbau klar ist) Bisschen schickere Kästen, abgerundete Ecken oder nur Border, oder so?! (Kann gerne mal ne halbe Stunde experimentieren und einen Vorschlag machen, wenn)

Hoffe das klingt nicht zu hart. Vielen Dank für die schon investierte Arbeit!!
Vielleicht wäre auch eine Einleitung für die Veranstaltungen nicht schlecht, auf der Startseite. 
Und allgemein mehr Inhalte und Call to Actions (Projekte, mitmachen) auf der Startseite
Achso, der Bus könnte aus meiner Sicht auch so bleiben, wenn der Rest der Webseite genauso schnörkelige Linien bekäme. Glaube aber das ist mehr Arbeit, als einfach einen geradelinigen Bus zu nehmen 😉

![Image](https://github.com/user-attachments/assets/61e199ae-445a-47e9-a533-828a4a636131)
